In [1]:
import numpy as np

import xgboost as xgb
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split    
from sklearn.metrics import confusion_matrix
from sklearn import datasets

from sklearn.model_selection import GridSearchCV

import matplotlib.pyplot as plt

import seaborn as sns

from sklearn.ensemble import RandomForestClassifier


In [2]:
# Carregar o dataset MNIST
digits = datasets.load_digits(n_class=10)

images=digits.images
targets=digits.target
images=images.reshape(len(images),8*8)

X = digits.data
y = digits.target

# Dividir o dataset em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(images, targets, test_size=0.2)

In [3]:
modelo = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, criterion='gini')
modelo.fit(X_train, y_train)

y_pred=modelo.predict(X_test)

acuracia = accuracy_score(y_test, y_pred)
print("Acurácia: %.2f%%" % (acuracia * 100.0))

confusion = confusion_matrix(y_test, y_pred)
print('Matriz de Confusão\n')
print(confusion)

Acurácia: 97.22%
Matriz de Confusão

[[39  0  0  0  1  0  0  0  0  0]
 [ 0 41  0  0  0  0  0  0  0  0]
 [ 1  0 36  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  1  0]
 [ 0  0  0  0 41  0  0  0  0  1]
 [ 0  0  0  0  0 32  1  0  0  1]
 [ 0  0  0  0  0  0 40  0  0  0]
 [ 0  0  0  0  0  0  0 30  0  0]
 [ 0  0  3  0  0  0  0  0 23  0]
 [ 0  0  0  1  0  0  0  0  0 34]]
